#keys are int values (convert hex to int)
internal_character_id = {
    0 : "Mario",
    1 : "Fox",
    2 : "Captain Falcon",
    3 : "Donkey Kong",
    4 : "Kirby",
    5 : "Bowser",
    6 : "Link",
    7 : "Shiek",
    8 : "Ness",
    9 : "Peach",
    10 : "Popo",
    11 : "Nana",
    12 : "Pikachu",
    13 : "Samus",
    14 : "Yoshi",
    15 : "Jigglypuff",
    16 : "Mewtwo",
    17 : "Luigi",
    18 : "Marth",
    19 : "Zelda",
    20 : "Young Link",
    21 : "Dr. Mario",
    22 : "Falco",
    23 : "Pichu",
    24 : "Mr. Game and Watch",
    25 : "Ganondorf",
    26 : "Roy"
}

external_character_id = {
    0 : "Captain Falcon",
    1 : "Donkey Kong",
    2 : "Fox",
    3 : "Mr. Game and Watch",
    4 : "Kirby",
    5 : "Bowser",
    6 : "Link",
    7 : "Luigi",
    8 : "Mario",
    9 : "Marth",
    10 : "Mewtwo",
    11 : "Ness",
    12 : "Peach",
    13 : "Pikachu",
    14 : "Ice Climbers",
    15 : "Jigglypuff",
    16 : "Samus",
    17 : "Yoshi",
    18 : "Zelda",
    19 : "Shiek",
    20 : "Falco",
    21 : "Young Link",
    22 : "Dr. Mario",
    23 : "Roy",
    24 : "Pichu",
    25 : "Ganondorf",
    26 : "None"
}

stage_index = {
    2 : "Fountain of Dreams",
    3 : "Pokemon Stadium",
    4 : "Peach's Castle",
    5 : "Kongo Jungle",
    6 : "Brinstar",
    7 : "Corneria",
    8 : "Yoshi's Story",
    9 : "Onett",
    10 : "Mute City",
    11 : "Rainbow Cruise",
    12 : "Jungle Japes",
    13 : "Great Bay",
    14 : "Hyrule Temple",
    15 : "Brinstar Depths",
    16 : "Yoshi's Island",
    17 : "Green Greens",
    18 : "Fourside",
    19 : "Mushroom Kingdom 1",
    20 : "Mushroom Kingdom 2",
    21 : "Akaneia",
    22 : "Venom",
    23 : "Poke Floats",
    24 : "Big Blue",
    25 : "Icicle Mountain",
    26 : "Icetop",
    27 : "Flat Zone",
    28 : "Dreamland 64",
    29 : "Yoshi's Island 64",
    30 : "Kongo Jungle 64",
    31 : "Battlefield",
    32 : "Final Destination"
}

#unfinished
#skipped unimportant stuff after 111
action_state_id = {
    0 : "KO Down",
    1 : "KO Left",
    2 : "KO Right",
    3 : "KO Up",
    4 : "Star KO",
    5 : "Ice Star KO",
    6 : "Front Fall KO",
    7 : "Hit Camera KO",
    8 : "Hit Camera Flat KO",
    9 : "Front Fall Ice KO",
    10 : "Hit Camera Ice KO",
    11 : "Sleep",
    12 : "Respawn",
    13 : "Respawn Wait",
    14 : "Stand",
    15 : "Walk Slow",
    16 : "Walk Middle",
    17 : "Walk Fast",
    18 : "Turn",
    19 : "Turn Run",
    20 : "Dash",
    21 : "Run",
    22 : "Run Direct",
    23 : "Run Brake",
    24 : "Jumpsquat",
    25 : "Jump Forward",
    26 : "Jump Backward",
    27 : "Jump Aerial Forward",
    28 : "Jump Aerial Forward",
    29 : "Jump Aerial Backward",
    30 : "Fall Forward",
    31 : "Fall Backward",
    32 : "Fall Aerial",
    33 : "Fall Aerial Forward",
    34 : "Fall Aerial Backward",
    35 : "Fall Special",
    36 : "Fall Special Forward",
    37 : "Fall Special Backward",
    38 : "Tumble",
    39 : "Squat",
    40 : "Crouch",
    41 : "Stand Up",
    42 : "Landing",
    43 : "Special Fall Landing",
    44 : "Jab",
    45 : "Jab 2",
    46 : "Jab 3",
    47 : "Jab Loop Startup",
    48 : "Jab Loop",
    49 : "Jab Loop Endlag",
    50 : "Dash Attack",
    51 : "High Forward Tilt",
    52 : "High-Mid Forward Tilt",
    53 : "Mid Forward Tilt",
    54 : "Mid-Low Forward Tilt",
    55 : "Low Forward Tilt",
    56 : "Up Tilt",
    57 : "Down Tilt",
    58 : "High Forward Smash",
    59 : "High-Mid Forward Smash",
    60 : "Mid Forward Smash",
    61 : "Mid-Low Forward Smash",
    62 : "Low Forward Smash",
    63 : "Upsmash",
    64 : "Downsmash",
    65 : "Neutral Air",
    66 : "Forward Air",
    67 : "Back Air",
    68 : "Up Air",
    69 : "Down Air",
    70 : "Nair Landing",
    71 : "Fair Landing",
    72 : "Bair Landing",
    73 : "Uair Landing",
    74 : "Dair Landing",
    75 : "Damage Hi1",
    76 : "Damage Hi2",
    77 : "Damage Hi3",
    78 : "Damage N1",
    79 : "Damage N2",
    80 : "Damage N3",
    81 : "Damage Lw1",
    82 : "Damage Lw2",
    83 : "Damage Lw3",
    84 : "Damage Air1",
    85 : "Damage Air2",
    86 : "Damage Air3",
    87 : "Damage FlyHi",
    88 : "Damage FlyN",
    89 : "Damage FlyLw",
    90 : "Damage FlyTop",
    91 : "Damage FlyRoll",
    92 : "Light Item Pickup",
    93 : "Heavy Item Pickup",
    94 : "Light Throw Forward",
    95 : "Light Throw Backward",
    96 : "Light Throw High",
    97 : "Light Throw Low",
    98 : "Light Throw Dash",
    99 : "Light Throw Drop",
    100 : "Light Throw Air Forward",
    101 : "Light Throw Air Backward",
    102 : "Light Throw Air High",
    103 : "Light Throw Air Low",
    104 : "Heavy Throw Forward",
    105 : "Heavy Throw Backward",
    106 : "Heavy Throw High",
    107 : "Heavy Throw Low",
    108 : "Light Throw Forward Smash",
    109 : "Light Throw Backward Smash",
    110 : "Light Throw High Smash",
    111 : "Light Throw Low Smash",
    178 : "Shield On",
    179 : "Shielding",
    180 : "Lower Shield",
    181 : "Shield Stun",
    182 : "Perfect Shield",
    183 : "Bounce Face Up",
    184 : "Laying Face Up",
    185 : "Laying Damaged Up",
    186 : "Down Stand",
    187 : "Get Up Attack",
    188 : "Down Forward Up",
    189 : "Down Back Up",
    190 : "Down Spot Up",
    191 : "Bounce Face Down",
    192 : "Laying Face Down",
    193 : "Laying Damaged Down",
    194 : "Neutral Getup",
    195 : "Get Up Attack",
    196 : "Down Forward Down",
    197 : "Down Backward Down",
    198 : "Down Spot Down",
    199 : "Neutral Tech",
    200 : "Forward Tech Roll",
    201 : "Backward Tech Roll",
    202 : "Wall Tech",
    203 : "Wall Jump",
    204 : "Ceiling Tech",
    205 : "Shield Break Fly",
    206 : "Shield Break Fall",
    207 : "Shield Break Down U",
    208 : "Shield Break Down D",
    209 : "Shield Break Stand U",
    210 : "Shield Break Stand D",
    211 : "Shield Break Dizzy",
    212 : "Grab",
    213 : "Grab Pull",
    214 : "Dash Grab",
    215 : "Dash Grab Pull",
    216 : "Grab Hold",
    217 : "Grab Pummel",
    218 : "Grab Release",
    219 : "Forward Throw",
    220 : "Back Throw",
    221 : "Up Throw",
    222 : "Down Throw",
    223 : "Captured Pull High",
    224 : "Captured Wait",
    225 : "Captured Damage High",
    226 : "Captured Pull Low",
    227 : "Captured Wait Low",
    228 : "Captured Damage Low",
    229 : "Captured Break",
    230 : "Captured Jump",
    231 : "Captured Neck",
    232 : "Captured Foot",
    233 : "Forward Roll",
    234 : "Back Roll",
    235 : "Spot Dodge",
    236 : "Air Dodge",
    237 : "Rebound Stop",
    238 : "Rebound",
    239 : "Thrown Forward",
    240 : "Thrown Backward",
    241 : "Thrown Up",
    242 : "Thrown Down",
    243 : "Thrown Down Women",
    244 : "Platform Drop",
    245 : "Ledge Teeter",
    246 : "Ledge Teeter Wait",
    247 : "Fly Reflect Wall",
    248 : "Fly Reflect Ceiling",
    249 : "Stop Wall",
    250 : "Stop Ceiling",
    251 : "Miss Foot",
    252 : "Ledge Catch",
    253 : "Ledge Hang",
    254 : "Ledge Getup Slow",
    255 : "Ledge Getup Quick",
    256 : "Ledge Attack Slow",
    257 : "Ledge Attack Quick",
    258 : "Ledge Roll Slow",
    259 : "Ledge Roll Quick",
    260 : "Tournament Winner Slow 1",
    261 : "Tournament Winner Slow 2",
    262 : "Tournament Winner Quick 1",
    263 : "Tournament Winner Quick 2",
    264 : "Taunt Right",
    265 : "Taunt Left",
    266 : "Shouldered Wait",
    267 : "Shouldered Walk Slow",
    268 : "Shouldered Walk Middle",
    269 : "Shouldered Walk Fast",
    270 : "Shouldered Turn",
    271 : "Thrown FF",
    272 : "Thrown FB",
    273 : "Thrown F High",
    274 : "Thrown F Low",
    275 : "Capture Captain",
    276 : "Capture Yoshi",
    277 : "Yoshi Egg",
    278 : "Bowser Grab",
    279 : "Bowser Pummel",
    280 : "Bowser Hold",
    281 : "Bowser Forward Throw",
    282 : "Bowser Back Throw",
    283 : "Bowser Grab Air",
    284 : "Bowser Pummel Air",
    285 : "Bowser Hold Air",
    286 : "Thrown Forward Koopa",
    287 : "Thrown Backward Koopa",
    322 : "Entry",
    323 : "Entry Start",
    324 : "Entry End"
}

#Fox's special action ID table
fox_special_action_id = {
    341 : "Grounded Laser Startup",
    342 : "Grounded Laser",
    343 : "Grounded Laser Endlag",
    344 : "Aerial Laser Startup",
    345 : "Aerial Laser",
    346 : "Aerial Laser Endlag",
    347 : "Grounded Illusion Startup",
    348 : "Grounded Illusion",
    349 : "Grounded Illusion Endlag",
    350 : "Aerial Illusion Startup",
    351 : "Aerial Illusion",
    352 : "Aerial Illusion Endlag",
    353 : "Fire Fox Startup",
    354 : "Fire Fox",
    355 : "Fire Fox",
    356 : "Fire Fox",
    357 : "Fire Fox",
    358 : "Fire Fox",
    359 : "Fire Fox Endlag",
    360 : "Grounded Shine Startup",
    361 : "Shine",
    363 : "Grounded Shine Endlag",
    365 : "Aerial Shine Startup",
    366 : "Shine",
    368 : "Aerial Shine Endlag"
}
