internal_character_id = {
    0 : "Mario",
    1 : "Fox",
    2 : "Captain Falcon",
    3 : "Donkey Kong",
    4 : "Kirby",
    5 : "Bowser",
    6 : "Link",
    7 : "Shiek",
    8 : "Ness",
    9 : "Peach",
    10 : "Popo",
    11 : "Nana",
    12 : "Pikachu",
    13 : "Samus",
    14 : "Yoshi",
    15 : "Jigglypuff",
    16 : "Mewtwo",
    17 : "Luigi",
    18 : "Marth",
    19 : "Zelda",
    20 : "Young Link",
    21 : "Dr. Mario",
    22 : "Falco",
    23 : "Pichu",
    24 : "Mr. Game and Watch",
    25 : "Ganondorf",
    26 : "Roy"
}

external_character_id = {
    0 : "Captain Falcon",
    1 : "Donkey Kong",
    2 : "Fox",
    3 : "Mr. Game and Watch",
    4 : "Kirby",
    5 : "Bowser",
    6 : "Link",
    7 : "Luigi",
    8 : "Mario",
    9 : "Marth",
    10 : "Mewtwo",
    11 : "Ness",
    12 : "Peach",
    13 : "Pikachu",
    14 : "Ice Climbers",
    15 : "Jigglypuff",
    16 : "Samus",
    17 : "Yoshi",
    18 : "Zelda",
    19 : "Shiek",
    20 : "Falco",
    21 : "Young Link",
    22 : "Dr. Mario",
    23 : "Roy",
    24 : "Pichu",
    25 : "Ganondorf"
}

stage_index = {
    2 : "Fountain of Dreams",
    3 : "Pokemon Stadium",
    4 : "Peach's Castle",
    5 : "Kongo Jungle",
    6 : "Brinstar",
    7 : "Corneria",
    8 : "Yoshi's Story",
    9 : "Onett",
    10 : "Mute City",
    11 : "Rainbow Cruise",
    12 : "Jungle Japes",
    13 : "Great Bay",
    14 : "Hyrule Temple",
    15 : "Brinstar Depths",
    16 : "Yoshi's Island",
    17 : "Green Greens",
    18 : "Fourside",
    19 : "Mushroom Kingdom 1",
    20 : "Mushroom Kingdom 2",
    21 : "Akaneia",
    22 : "Venom",
    23 : "Poke Floats",
    24 : "Big Blue",
    25 : "Icicle Mountain",
    26 : "Icetop",
    27 : "Flat Zone",
    28 : "Dreamland 64",
    29 : "Yoshi's Island 64",
    30 : "Kongo Jungle 64",
    31 : "Battlefield",
    32 : "Final Destination"
}

#unfinished 74/382
action_state_id = {
    0 : "KO Down",
    1 : "KO Left",
    2 : "KO Right",
    3 : "KO Up",
    4 : "Star KO",
    5 : "Ice Star KO",
    6 : "Front Fall KO",
    7 : "Hit Camera KO",
    8 : "Hit Camera Flat KO",
    9 : "Front Fall Ice KO",
    10 : "Hit Camera Ice KO",
    11 : "Sleep",
    12 : "Respawn",
    13 : "Respawn Wait",
    14 : "Stand",
    15 : "Walk Slow",
    16 : "Walk Middle",
    17 : "Walk Fast",
    18 : "Turn",
    19 : "Turn Run",
    20 : "Dash",
    21 : "Run",
    22 : "Run Direct",
    23 : "Run Brake",
    24 : "Jumpsquat",
    25 : "Jump Forward",
    26 : "Jump Backward",
    27 : "Jump Aerial Forward",
    28 : "Jump Aerial Forward",
    29 : "Jump Aerial Backward",
    30 : "Fall Forward",
    31 : "Fall Backward",
    32 : "Fall Aerial",
    33 : "Fall Aerial Forward",
    34 : "Fall Aerial Backward",
    35 : "Fall Special",
    36 : "Fall Special Forward",
    37 : "Fall Special Backward",
    38 : "Tumble",
    39 : "Squat",
    40 : "Crouch",
    41 : "Stand Up",
    42 : "Landing",
    43 : "Special Fall Landing",
    44 : "Jab",
    45 : "Jab 2",
    46 : "Jab 3",
    47 : "Jab Loop Startup",
    48 : "Jab Loop",
    49 : "Jab Loop Endlag",
    50 : "Dash Attack",
    51 : "High Forward Tilt",
    52 : "High-Mid Forward Tilt",
    53 : "Mid Forward Tilt",
    54 : "Mid-Low Forward Tilt",
    55 : "Low Forward Tilt",
    56 : "Up Tilt",
    57 : "Down Tilt",
    58 : "High Forward Smash",
    59 : "High-Mid Forward Smash",
    60 : "Mid Forward Smash",
    61 : "Mid-Low Forward Smash",
    62 : "Low Forward Smash",
    63 : "Upsmash",
    64 : "Downsmash",
    65 : "Neutral Air",
    66 : "Forward Air",
    67 : "Back Air",
    68 : "Up Air",
    69 : "Down Air",
    70 : "Nair Landing",
    71 : "Fair Landing",
    72 : "Bair Landing",
    73 : "Uair Landing",
    74 : "Dair Landing"
}
