internal_character_id = {
    0 : "Mario",
    1 : "Fox",
    2 : "Captain Falcon",
    3 : "Donkey Kong",
    4 : "Kirby",
    5 : "Bowser",
    6 : "Link",
    7 : "Shiek",
    8 : "Ness",
    9 : "Peach",
    10 : "Popo",
    11 : "Nana",
    12 : "Pikachu",
    13 : "Samus",
    14 : "Yoshi",
    15 : "Jigglypuff",
    16 : "Mewtwo",
    17 : "Luigi",
    18 : "Marth",
    19 : "Zelda",
    20 : "Young Link",
    21 : "Dr. Mario",
    22 : "Falco",
    23 : "Pichu",
    24 : "Mr. Game and Watch",
    25 : "Ganondorf",
    26 : "Roy"
}

external_character_id = {
    0 : "Captain Falcon",
    1 : "Donkey Kong",
    2 : "Fox",
    3 : "Mr. Game and Watch",
    4 : "Kirby",
    5 : "Bowser",
    6 : "Link",
    7 : "Luigi",
    8 : "Mario",
    9 : "Marth",
    10 : "Mewtwo",
    11 : "Ness",
    12 : "Peach",
    13 : "Pikachu",
    14 : "Ice Climbers",
    15 : "Jigglypuff",
    16 : "Samus",
    17 : "Yoshi",
    18 : "Zelda",
    19 : "Shiek",
    20 : "Falco",
    21 : "Young Link",
    22 : "Dr. Mario",
    23 : "Roy",
    24 : "Pichu",
    25 : "Ganondorf"
}

stage_index = {
    2 : "Fountain of Dreams",
    3 : "Pokemon Stadium",
    4 : "Peach's Castle",
    5 : "Kongo Jungle",
    6 : "Brinstar",
    7 : "Corneria",
    8 : "Yoshi's Story",
    9 : "Onett",
    10 : "Mute City",
    11 : "Rainbow Cruise",
    12 : "Jungle Japes",
    13 : "Great Bay",
    14 : "Hyrule Temple",
    15 : "Brinstar Depths",
    16 : "Yoshi's Island",
    17 : "Green Greens",
    18 : "Fourside",
    19 : "Mushroom Kingdom 1",
    20 : "Mushroom Kingdom 2",
    21 : "Akaneia",
    22 : "Venom",
    23 : "Poke Floats",
    24 : "Big Blue",
    25 : "Icicle Mountain",
    26 : "Icetop",
    27 : "Flat Zone",
    28 : "Dreamland 64",
    29 : "Yoshi's Island 64",
    30 : "Kongo Jungle 64",
    31 : "Battlefield",
    32 : "Final Destination"
}
